#ifndef __CONFIG_H
#define __CONFIG_H

#define _ALIGN_CEILING(n, align) (((n) + (align) - 1) / (align) * (align))

#define FLASH_SIZE ((size_t)64 * 1024 * 1024 * 1024)
#define SSD_SIZE _ALIGN_CEILING((FLASH_SIZE*100/(100+CONFIG_NAND_OP_RATIO_X100)),4096)

#define CONFIG_NR_HOST_IO_REQS 65536
#define CONFIG_NR_SSD_ADMIN_REQS 64

#define CONFIG_GET_TIME_FLOAT

#define CONFIG_ACCESS_EXACT_PPA 1

// #define CONFIG_TEST_NEON
// #define CONFIG_REPLAY_TRACE
#define CONFIG_NR_CS_ARGS_REQS 128
#define CONFIG_NR_CS_REQS CONFIG_NR_CS_ARGS_REQS
#define CONFIG_NR_CS_IO_REQS 2048
// #define CONFIG_NR_CS_FILES 128
// #define CONFIG_CS_FILE_INDEX_DEFAULT_LEN 512
// #define CONFIG_CS_FILE_MAX_PENDING_REQS 128

#define CONFIG_CS_SGIO_MAX_PENDING_REQS 128

#define CONFIG_ENABLE_L2P_MAPPING_DEFAULT 1
#define CONFIG_ENABLE_NAND_LATENCY_EMU_DEFAULT 0
#define CONFIG_ENABLE_DSM_DEFAULT 1

#define CONFIG_NAND_SECTORS_SIZE 4096
// #define CONFIG_NAND_SECTORS_PER_PAGE 4
// #define CONFIG_NAND_PAGES_PER_BLOCK 128 // 2MB, align with f2fs segment size
#define CONFIG_NAND_SECTORS_PER_PAGE 1
#define CONFIG_NAND_PAGES_PER_BLOCK 512 // 2MB, align with f2fs segment size
#define CONFIG_NAND_LUNS_PER_CHANNEL 2
#define CONFIG_NAND_CHANNELS 8
#define CONFIG_NAND_OP_RATIO_X100 7
// #define CONFIG_NAND_OP_RATIO_X100 0
#define CONFIG_NAND_READ_LATENCY 80000
#define CONFIG_NAND_PROG_LATENCY 400000
#define CONFIG_NAND_ERASE_LATENCY 0
#define CONFIG_GC_THRESHOLD 0.75
#define CONFIG_GC_THRESHOLD_HIGH 0.95

#endif
