SRC_WORKSPACE_PATH=/home/jin/workspaces/csgc
DST_WORKSPACE_PATH=/home/jin/workspaces/csgc2

VITIS_FTL_PROJECT_NAME=ftl
VITIS_CS_PROJECT_NAME=cs_leader
VITIS_CS_WORKER1_PROJECT_NAME=cs_worker1
VITIS_CS_WORKER2_PROJECT_NAME=cs_worker2

sudo cp -r ${SRC_WORKSPACE_PATH}/${VITIS_FTL_PROJECT_NAME}/src ${DST_WORKSPACE_PATH}/${VITIS_FTL_PROJECT_NAME}
sudo cp -r ${SRC_WORKSPACE_PATH}/${VITIS_CS_PROJECT_NAME}/src ${DST_WORKSPACE_PATH}/${VITIS_CS_PROJECT_NAME}
sudo cp -r ${SRC_WORKSPACE_PATH}/${VITIS_CS_WORKER1_PROJECT_NAME}/src ${DST_WORKSPACE_PATH}/${VITIS_CS_WORKER1_PROJECT_NAME}
sudo cp -r ${SRC_WORKSPACE_PATH}/${VITIS_CS_WORKER2_PROJECT_NAME}/src ${DST_WORKSPACE_PATH}/${VITIS_CS_WORKER2_PROJECT_NAME}